package com.mativimu.eventsappservice.entities.participant;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import com.mativimu.eventsappservice.entities.event.Event;
import com.mativimu.eventsappservice.entities.user.User;

@Entity
@Table(name = "participants")
public class Participant {
    
    @Id
    @Column(name = "participant_id", nullable = false, unique = true )
    private Long participantId;

    @Column(name = "participant_status", nullable = false, length = 8)
    private String participantStatus;

    @Column(name = "attendance_proved", nullable = false, length = 10)
    private String attendanceProved;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "user_id")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id", referencedColumnName = "event_id")
    private Event event;

    // participantID is generated by the sum of both eventID and userID to avoid duplicity
    public Participant(String participantStatus, User user, Event event) {
        this.participantStatus = participantStatus;
        setAttendanceProved("false");
        this.user = user;
        this.event = event;
        setParticipantId();
    }

    public Participant() {}
    
    public Long getParticipantId(){
        return this.participantId;
    }

    public void setParticipantId() {
        this.participantId = this.event.getEventId() + this.user.getUserId();
    }

    public String getParticipantStatus() {
        return participantStatus;
    }

    public void setParticipantStatus(String participantStatus) {
        this.participantStatus = participantStatus;
    }

    public String getAttendanceProved() {
        return attendanceProved;
    }

    public void setAttendanceProved(String attendanceProved) {
        this.attendanceProved = attendanceProved;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }
    
}
